Update dependencies and install with npm instead of yarn
`npm run start` currently fails with:

```
> npm run start

> katy-hiking-trails-react-native@0.1.0 start
> expo start

Starting project at /Users/christophernady/Development/code/katy-hiking-trails-react-native
Starting Metro Bundler
CommandError: The bundled native module list from the Expo API is empty
```

`yarn start` was failing with a similar error:

```
> yarn start
yarn run v1.22.19
$ expo start
Starting project at /Users/christophernady/Development/code/katy-hiking-trails-react-native
Starting Metro Bundler
CommandError: The bundled native module list from the Expo API is empty
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```